# Generated by Django 3.0.8 on 2020-08-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200830_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='computer-icons-user-profile-male-avatar-avatar-png-clip-art.png', null=True, upload_to=''),
        ),
    ]
